### ISSUE TITLE
chokidar use trips on large sub-directory trees

### ISSUE THREAD

**Issue by smokku** [glen-84/vscode-sass-lint#10] opened 2017-04-05 00:12 UTC
server code
```js
const watcher = chokidar.watch(`**/${CONFIG_FILE_NAME}`, ...
```
will create watcher for every directory in project - in case `CONFIG_FILE_NAME` file appears in one.

This trips on projects with a lot of directories (for example project with long development history, thus many dirs and files in `.git` dir).

```
Error: watch .git/objects/1b ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at createFsWatchInstance (/home/smoku/.vscode/extensions/glen-84.sass-lint-0.0.3/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
...
```

**Comment by glen-84** [comment] 2017-04-09 18:43
Closing as a duplicate of #6.

This is quite possibly fixed in v0.0.4.

**Closed as completed by glen-84** 2017-04-09 18:43 UTC
Labels: duplicate
