### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by wagenet** [glen-84/vscode-sass-lint#2] opened 2016-08-02 15:44 UTC
This extension works, but causes very high CPU usage.

**Comment by glen-84** [comment] 2016-08-02 16:01
@wagenet Please update your comment to include some more information, such as:
- OS
- VS Code version
- Node.js version
- sass-lint version
- How many sass/scss files open
- CPU high always or while typing
- Extension configuration
- etc.

**Comment by wagenet** [comment] 2016-08-03 22:38
OS: OS X 10.11.6
VSCode: 1.4.0-insiders
Node: 4.4.7
sass-lint: 1.8.2

Only a handful of files open at a time at most.
CPU always high even when not typing.
No further special configuration.

**Comment by glen-84** [comment] 2016-08-06 17:52
Peter,

I'm not able to reproduce this on Windows 10 (VS Code 1.4.0), and a co-worker is also not able to reproduce the issue on OS X (Node 6.2.1).

Are you using the default (built-in) rules, or have you specified a `configFile`?

Here are a few things to confirm and/or try:
1. VS Code without extensions
2. VS Code with _just_ this extension
3. VS Code with _just_ an extension like tslint (similar code)
4. Updated Node version (6.x)
5. Another machine (with OS X)
6. Running sass-lint from a console (to observe CPU usage)

If none of the above uncovers anything, then I'm mostly out of ideas. :disappointed:

**Comment by itanex** [comment] 2016-08-25 05:02
I have found that FSEvent is actually the issue with VSC on OSX.

This isn't actually in VSC or vsc-sass-lint. FSEvent is actually utilized in Electron and that is where I have seen this issue arise. To reproduce this consistantly:
1. Have a working folder with 1000s of folders and files
2. Interact with several of the files over time
   or
3. Leave vsc open for a long duration, roughly 2-3 days

The team I work on this occurs frequently. Part of our workflow is to restart VSC every once and a while and it solves the problem.

This is also reported in other platforms that utilize Electron.

**Comment by johanbove** [comment] 2016-09-01 06:41
I'm experiencing the same issue. It happens when i have a .scss file open in the editor; after a while the "Code Helper" process is going over 100%. Without the extension I don't have the issue.

My environment:
OS: OS X 10.11.6
VSCode: 1.4.0
Node: 5.11.1
sass-lint: 1.9.0

My _.scss-lint.yml_ configuration file: 
[scss-lint.txt](https://github.com/glen-84/vscode-sass-lint/files/448972/scss-lint.txt)

**Comment by glen-84** [comment] 2016-09-03 19:21
@johanbove This extension is for [sass-lint](https://github.com/sasstools/sass-lint/) and not [scss-lint](https://github.com/brigade/scss-lint). =)

**Comment by johanbove** [comment] 2016-09-07 10:58
I see. Sorry. I thought sass-lint also did scss-lint ing. My bad.

**Comment by glen-84** [comment] 2016-09-07 12:03
@johanbove,

No worries. Sass-lint does lint `scss` files, but it won't work with an scss-lint configuration file.

**Comment by glen-84** [comment] 2016-10-02 13:31
Thanks for the info, @itanex.

I'm closing this for now.

**Comment by kmturley** [comment] 2017-01-24 18:04
I'm also getting very high CPU usage of 140% even after excluding node, bower and jspm folders.

MacOS: 10.10.5
VS Code: 1.8.1
Node.js: v6.9.2
sass-lint: 1.10.2
vscode-sass-lint: 0.0.3
How many sass/scss files open: 1
CPU high always or while typing: always high
Extension configuration: none

I switched to using this extension and not having the same issue:
https://marketplace.visualstudio.com/items?itemName=adamwalzer.scss-lint

I believe it's an issue with the way your extension works. See screenshots below:

<img width="742" alt="screen shot 2017-01-24 at 1 00 20 pm" src="https://cloud.githubusercontent.com/assets/1710493/22259944/4120d55a-e235-11e6-8b99-869508aeb2ba.png">
<img width="755" alt="screen shot 2017-01-24 at 1 01 17 pm" src="https://cloud.githubusercontent.com/assets/1710493/22259945/41221abe-e235-11e6-8ad7-724d15d9c670.png">

**Comment by glen-84** [comment] 2017-01-24 18:33
@kmturley `sass-lint` and `scss-lint` are different – is your configuration file compatible with [sass-lint](https://github.com/sasstools/sass-lint)?

If it is, adding it here, along with a test file, might help to diagnose the issue, but unfortunately I don't have access to a MacOS machine, so it may be difficult for me to reproduce the issue.

Edit: Please also mention which version of `sass-lint` (the library, not this extension) you have installed.

**Comment by kmturley** [comment] 2017-01-24 19:09
I tried with, and without a configuration file, same issue. I think it might be down the the project size. When I run:

    find . -type f | wc -l

I get a total of 53,106 files/folders including node_modules, jspm_packages and bower_components folders

**Comment by glen-84** [comment] 2017-01-28 14:51
That shouldn't really be an issue. As far as I know, it doesn't scan all files, it only passes the active file to the `sass-lint` library.

Do you have the latest version of [sass-lint](https://github.com/sasstools/sass-lint) installed?

**Comment by kmturley** [comment] 2017-01-28 15:35
I'm using 
sass-lint: 1.10.2
vscode-sass-lint: 0.0.3

Which is the latest version:
https://github.com/sasstools/sass-lint

**Comment by glen-84** [comment] 2017-02-05 09:05
Unfortunately I'm still not able to reproduce this issue.

If you can upload or reference a project that shows this problem, I can take another look.

**Comment by kmturley** [comment] 2017-02-07 22:41
It seems to be directly related to the number of folders in the project. Try this:
(WARNING it will create 6000 folders!)

    mkdir folders
    cd folders/
    mkdir folder{1..6000}

Then place a .sass-lint.yml inside the folder containing:

    rules:
      indentation:
        - 2
        -
          size: 4

And open the project to see the high CPU in Activity Monitor. the more folders, the higher the CPU

**Comment by glen-84** [comment] 2017-02-12 11:34
On Windows 10, with 10,000 folders, I only see the CPU spiking when I save a Sass file. This is a bit strange though, because it's configured to run the linter while typing (changing) the document, and not when saving it.

I'll re-open this for now. I might run some tests with and without the current file watchers.

**Comment by hilleer** [comment] 2017-03-01 09:44
Having the same issue on macOS Sierra version 10.12.3.

**Comment by gokhanozdemir** [comment] 2017-03-15 09:51
I also have the same issue :/ 

The interesting thing is it does not show up on my other mac :/ 
<img width="1156" alt="screen shot 2017-03-15 at 12 05 54" src="https://cloud.githubusercontent.com/assets/8511119/23940790/efabf784-096e-11e7-9260-523702f264df.png">

Later I also installed sass globally. Nothing changes.

**Comment by jlengstorf** [comment] 2017-03-16 20:44
I just confirmed this issue on my Mac (macOS 10.12.3). I've ignored all the usual suspects — `node_modules`, etc. — in Code's settings (`files.watcherExclude`), and it spikes hard in a relatively small repo. (If you don't consider the `node_modules` and such, that is.)

My `.sass-lint.yml` is pretty bare-bones:

```
options:
  formatter: stylish
rules:
    class-name-format:
      - 1
      - convention: hyphenatedbem
    variable-name-format:
      - 1
      - convention: hyphenatedbem
```

**Comment by glen-84** [comment] 2017-03-19 14:56
I'm really short on time lately, and it might still be a few weeks before I am able to look into this properly. I do apologize for that.

@gokhanozdemir, could you compare as many versions as possible between your Macs? (OS, sass-lint, VS Code, etc.)

Also, is it the same project that you have open? Do both VS Code instances use the same extensions? etc.

**Comment by glen-84** [comment] 2017-03-19 15:27
Could be related to https://github.com/Microsoft/vscode/issues/3998.

**Comment by melv-n** [comment] 2017-03-20 22:18
Same issue here, runs my fans crazy. Figured out it was sass-lint by `ps aux`ing the process:
```
$ ps aux | grep 46506
USER           46506 104.0  1.6  3461800 270468   ??  R    11:11PM   0:43.10 /Applications/Visual 
Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper 
/Users/USER/.vscode/extensions/glen-84.sass-lint-0.0.3/node_modules/vscode-
languageclient/lib/utils/electronForkStart /Users/USER/.vscode/extensions/glen-84.sass-lint-
0.0.3/server/server.js --node-ipc
```

I took have excluded almost all folders in `settings.json`, such as `.git`, `node_modules`, etc.

**Comment by smokku** [comment] 2017-04-05 00:13
Possibly related to #10

**Comment by glen-84** [comment] 2017-04-05 07:13
@smokku Yes, I realized this recently – I'm just trying to find time to work on it.

I want to see if I can make use of the watcher exclude list in VS Code, but I haven't yet looked into it.

I hope to have some time within the next 2 weeks.

**Comment by gokhanozdemir** [comment] 2017-04-05 08:52
@glen-84 I somehow missed the notification, sorry. I had 2 macs and both had the issue when I was trying to solve the issue. I hope this weekend I will download an older version of VS Code and progress step by step. 

Keep being great @glen-84 !

**Comment by glen-84** [comment] 2017-04-09 10:12
Hey guys,

I just released a new version of the extension (v0.0.4). Can you please let me know if it fixes this issue?

Thanks.

**Comment by gokhanozdemir** [comment] 2017-04-09 14:05
@glen-84 YES YES YEEEES it fixed for me. :)
VS Code Version 1.10.2 + than made an update for VS Code Version 1.11.1
Mac OS Sierra 10.12.4 

Thanks.

**Comment by jlengstorf** [comment] 2017-04-11 15:00
@glen-84 It appears to be fixed for me as well. (Sass Lint 0.0.4, VS Code 1.11.1, macOS 10.12.4)

**Comment by melv-n** [comment] 2017-04-12 08:47
I haven't run into this issue since the update, looks promising!

**Comment by glen-84** [comment] 2017-04-14 14:20
Great. I'll close this issue now.

**Closed as completed by glen-84** 2017-04-14 14:20 UTC
Labels: bug
