### ISSUE TITLE
Sass lint doesn't work anymore

### ISSUE THREAD

**Issue by naxsooley** [glen-84/vscode-sass-lint#6] opened 2016-10-17 07:16 UTC
Sass lint became broken after the latest VSCode update.

I get these errors each time I launch vscode:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch node_modules/gulp.spritesmith/node_modules/xtend ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at createFsWatchInstance (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:74:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)
[Info  - 10:11:05 AM] Connection to server got closed. Server will restart.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch node_modules/gulp.spritesmith/test/test-files ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at createFsWatchInstance (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:74:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)
[Info  - 10:11:10 AM] Connection to server got closed. Server will restart.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch node_modules/gulp.spritesmith/test/expected-files ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at createFsWatchInstance (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:74:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)
[Info  - 10:11:14 AM] Connection to server got closed. Server will restart.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch node_modules/gulp.spritesmith/test/expected-files ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at createFsWatchInstance (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:74:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)
[Info  - 10:11:17 AM] Connection to server got closed. Server will restart.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch node_modules/handlebars/dist/amd ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at createFsWatchInstance (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:74:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/sooley/.vscode/extensions/glen-84.sass-lint-0.0.2/server/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)
[Error - 10:11:21 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by glen-84** [comment] 2016-10-17 07:37
You might have run out of disk space?

Also see: http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

**Comment by naxsooley** [comment] 2016-10-17 07:39
Nope, I've more than 100gb of free space. 
I'm using VSCode 1.6.1 on Ubuntu and Macbook, both have a same error.

**Comment by glen-84** [comment] 2016-11-05 19:49
@naxsooley Could you please try the latest version? (v0.0.3)

**Comment by cortopy** [comment] 2016-11-17 11:53
I'm also having the same errors. 

Thinking this may be a dependency issue, I have re-installed sass-lint using npm. I also have sass-node and sass (gem).

**Comment by glen-84** [comment] 2016-12-17 14:45
I'll need more information, such as:

* OS version
* VS Code version
* Node.js version
* sass-lint version
* How many sass/scss files open
* Extension configuration
* sass-lint configuration
* etc.

**Comment by cortopy** [comment] 2016-12-22 14:55
I haven't looked into this for a while but today I re-enabled sass lint and it started working. Many updates in the last month of various things, so I'm not sure what fixed it.

**Comment by glen-84** [comment] 2016-12-22 15:21
@cortopy Do you have the [Sass](https://marketplace.visualstudio.com/items?itemName=robinbentley.sass-indented) extension installed?

**Comment by glen-84** [comment] 2017-01-20 12:25
Closing, as I cannot reproduce the error, and there has not been a reply from the OP.

**Closed as completed by glen-84** 2017-01-20 12:25 UTC
Labels: cannot reproduce
