### ISSUE TITLE
VSCode-Sass-Lint does not find .sass-lint.yml files, no linting enabled

### ISSUE THREAD

**Issue by ghost** [glen-84/vscode-sass-lint#11] opened 2017-04-07 02:19 UTC
Unable to get Sass Lint to work in VS Code. Atom does not have this problem with sass-lint. Neither does Sublime Text 3, it is purely this plugin.

* OS: Windows 10 Pro x64
* VS Code version: 1.11.1 (also didn't work on earlier versions)
* Node version: v6.10.2 (the LTS version recommended by the Node.js website)
* Sass-lint version: 1.10.2
* Sass-lint installed globally
* .sass-lint.yml file located in the root directory

I have attached a screenshot of the files I'm working with. As you can see, the code is out of order compared to what the .sass-lint.yml file states (I'm using the one you can find on the Foundation Github page). And that's just one problem, it doesn't pick up on broken syntax or missing semi-colons etc.

You'll notice to the right, the .sass-lint.yml file is in the root for that folder (e.g. Foundation).

Both ESLint and HTMLHint work. This does not.

# Node Modules Installed Globally
![cmd](https://cloud.githubusercontent.com/assets/23663019/24782864/e46ba694-1b16-11e7-99ec-580cc4aedcae.png)

# Image of Workspace
![example](https://cloud.githubusercontent.com/assets/23663019/24782820/801f4e98-1b16-11e7-88e7-dd2b84446c91.png)

**Comment by glen-84** [comment] 2017-04-09 10:25
Hi Chris,

Which repository can I clone to reproduce this issue?

**Comment by ghost** [comment] 2017-04-11 16:52
@glen-84 I figured out that it was due to this line missing from the `package.json` file:

```json
"sasslintConfig": ".sass-lint.yml"
```

However, this does bring up the interesting point that this is not required for the Atom and Sublime Sass Lint extensions. So there seems to be a significantly different philosophy between supporters of these various text-editors. It might be worth putting a note down in the README for this extension just for that reason.

EDIT: It is also not necessary for the ESLint extension either which is also another factor to suggest a note in the README file, since it seems the standard adopted by other extensions was not to require this.

**Comment by glen-84** [comment] 2017-04-14 16:15
It should not be required, but I'm not able to reproduce this issue using the [foundation-sites
](https://github.com/zurb/foundation-sites) repository.

**Comment by ghost** [comment] 2017-04-14 16:22
@glen-84 perhaps it is a Windows thing... Normally I work on Mac, so using Windows was quite different for me.

Thanks for trying to reproduce though.

EDIT: Have you tried using sass-lint on a project without a package.json?

**Comment by glen-84** [comment] 2017-04-14 16:33
I'm using Windows 10 as well.

Is the repository that you are having issues with a public repository?

**Comment by ghost** [comment] 2017-04-14 17:04
@glen-84 no it is not...but I've tested it with a few blank projects (i.e. just some scss files, an index.html, .sass-lint.yml, and a package.json.

Doesn't seem to be a specific repository issue, just seems to be whenever there is a package.json file, Sass Lint won't work unless adding that line to the package.

**Comment by glen-84** [comment] 2017-04-14 17:29
That sounds really strange.

**Comment by glen-84** [comment] 2017-05-27 09:01
Closing, as I was not able to reproduce this issue.

**Closed as completed by glen-84** 2017-05-27 09:01 UTC
Labels: cannot reproduce

**Comment by MikaelLambert** [comment] 2018-03-20 16:53
@glen-84 I'm not 100% sure if I was able to reproduce this, but I was able to solve my problem by adding the same key to my package.json file.

I have a local install of both yarn and sass-lint so perhaps that was the missing information.

yarn: 1.5.1
sass-lint (npm): 1.12.1
VSCode: 1.21.1
sass-lint (your extension): 1.0.1

Hopefully this info helps. If you need some further reproduction info or want me to test further, just let me know. Thanks.
